version: "3.4"

networks:
  crawler_internal:
    driver: bridge

services:
  elastic_search:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    networks:
      - crawler_internal

  elastic_search_ui:
    image: appbaseio/dejavu
    container_name: elastic_search_ui
    ports:
      - "1358:1358"

  protobuf_sender_ui:
    image: gusaul/grpcox:latest
    container_name: protobuf_sender_ui
    ports:
      - "6969:6969"
    volumes:
      - /log:/log
      
  spark:
    image: bitnami/spark:2.4.6
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
        - crawler_internal
        
  spark-worker-1:
    image: bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports: 
      - '8081:8081'
    networks:
        - crawler_internal

  proxy:
        image: envoyproxy/envoy-alpine:v1.14.1
        ports:
        - 9901:9901
        - 10000:10000
        - 10001:10001
        volumes:
        - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml