version: "3.4"

networks:
  crawler_internal:
    driver: bridge

services:
  elastic_search:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    networks:
      - crawler_internal

  elastic_search_ui:
    image: appbaseio/dejavu
    container_name: elastic_search_ui
    ports:
      - "1358:1358"

  protobuf_sender_ui:
    image: gusaul/grpcox:latest
    container_name: protobuf_sender_ui
    ports:
      - "6969:6969"
    volumes:
      - /log:/log
      
  spark:
    image: test
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:  
      - '8080:8080'
      - '7077:7077'
    networks:
        - crawler_internal
        
  spark-worker:
    image: test
    # build:  
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=6
    networks:
        - crawler_internal
    links: 
          - spark
    
  proxy:
    container_name: proxy
    image: envoyproxy/envoy-alpine:v1.14.1
    networks:
      - crawler_internal
    restart: on-failure
    ports:
      - 9901:9901
      - 10000:10000
      - 10001:10001
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  proxy-for-vk_1:
    container_name: proxy-for-vk_1
    build:
      dockerfile: proxy-for-vk/Dockerfile_proxy_1
      context: .
    networks:
      - crawler_internal
    restart: on-failure
    ports:
      - 8010:8010

  proxy-for-vk_2:
    container_name: proxy-for-vk_2
    build:
      dockerfile: proxy-for-vk/Dockerfile_proxy_2
      context: .
    networks:
        - crawler_internal
    restart: on-failure
    ports:
      - 8020:8020