version: "2.1"

networks:
  vk-crawler_crawler_internal:
    external: true
    
services:
  java-crawler:
    container_name: java-crawler
    build:
      dockerfile: java-crawler/Dockerfile
      context: .
      args:
          VK_APP_KEY: 8316dfb98316dfb98316dfb9ee836518c6883168316dfb9dc4e32d3d3de2f857ccbd94e
          VK_APP_ID: 7587711
    ports:
      - "9090:9090"
    networks:
      - vk-crawler_crawler_internal
    depends_on: 
      java-data-processing:
        condition: service_healthy
      
  python-summarization-service:
    container_name: python-summarization-service
    build:
        dockerfile: python-summarizer/Dockerfile
        context: .
    networks:
      - vk-crawler_crawler_internal
    depends_on: 
        java-data-processing:
          condition: service_healthy
  
  java-data-processing:
    container_name: java-data-processing
    build:
      dockerfile: java-data-processing/Dockerfile
      context: .
    networks:
      - vk-crawler_crawler_internal
    # depends_on: 
    #   - python-summarization-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://java-data-processing:7071/health"]
      interval: 30s
      timeout: 10s
      retries: 5