version: "3.4"

networks:
  crawler_internal:
    driver: bridge

services:
  elastic_search:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    networks:
      - crawler_internal

  elastic_search_ui:
    image: appbaseio/dejavu
    container_name: elastic_search_ui
    ports:
      - "1358:1358"

  protobuf_sender_ui:
    image: gusaul/grpcox:latest
    container_name: protobuf_sender_ui
    ports:
      - "6969:6969"
    volumes:
      - /log:/log

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
        - crawler_internal
     
  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-1"
    depends_on:
       - spark-master
    ports:
      - "8081:8081"
    networks:
        - crawler_internal
  