version: "2.1"
services:
    proxy:
        image: envoyproxy/envoy-alpine:v1.14.1

        ports:
        - 9901:9901
        - 8081:8081
        - 8080:8080
        volumes:
        - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml