apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-skeleton.fullname" . }}
  labels:
  {{- include "backend-skeleton.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: grpc # important!
  selector:
  {{- include "backend-skeleton.selectorLabels" . | nindent 4 }}
